import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    container: {
      flex: 1,
      justifyContent: "center",
      padding: 15,
      backgroundColor: "#FFD700",
    },
    title: {
      fontSize: 45,
      fontWeight: "400",
      marginBottom: 3,
      alignSelf:"center",
      //fontFamily: "Times New Roman",
      fontStyle: "italic",
      color: "white",
      textShadowColor: "#000000",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 1,
    },
    picker: {
      width: "100%",
      height: 40,
      borderRadius: 10,
      borderWidth: 0.5,
      alignSelf: "center",
      marginBottom: 10,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      paddingLeft: 10,
      paddingRight: 15,
      backgroundColor: "white",
    },
    dropText: {
      width:"45%",
      height: 30,
    },
    input: {
      width: "100%",
      height: 40,
      borderColor: "black",
      borderWidth: 1,
      marginBottom: 10,
      paddingHorizontal: 10,
      backgroundColor: "white",
    },
    boxVerse: {
      marginBottom: 3,
      //backgroundColor: "white",
      borderRadius: 20,
      padding: 6,
    },
    verse: {    
      fontSize: 18,
      //fontFamily: "Times New Roman",
      fontStyle: "italic",
      color: "black",
      textShadowColor: "yellow",
      textShadowOffset: { width: 1, height: 1 },
      textShadowRadius: 1,
    },
    textarea: {
      width: "100%",
      height: 100,
      borderWidth: 1,
      marginBottom: 20,
      paddingHorizontal: 10,
      textAlignVertical: "top",
      backgroundColor: "white",
      borderColor: "black",
    },
    label: {
      fontSize: 15,
      fontWeight: "bold",
      borderColor: "#FFA500",
    },
    boxShare:{
      width: "100%",
      alignItems: "center",
      marginBottom: 3,
    },
    shared:{
      backgroundColor: "black",
      borderColor: "#FFA500",
      borderRadius: 50,
      paddingBottom: 5,
      paddingTop: 5,
    },
    sharedText:{
      color: "#ffffff",
      fontWeight:"bold",
      paddingHorizontal: 30,
      borderColor: "black",
    },
    icon:{
      width: 20,
      height: 20,
    },
    dropdownArea:{
      width: "100%",
      height: 300,
      borderRadius: 5,
      marginBottom: 10,
      backgroundColor:"white",
      borderColor:"black",
      elevation: 5,
      alignSelf: "center",
    },
    bookItem:{
      width: "98%",
      height: 50,
      borderBottomWidth: 0.5,
      borderBottomColor: "black",
      alignSelf: "center",
      justifyContent: "center",
      backgroundColor: "white",
      borderColor: "#FFA500",
    },
    modalElements: {
      flex: 1,
      justifyContent: "center",
      padding: 15,
      backgroundColor: "#FFD700",
    },
    headerModal: {
      flexDirection:"row",
      alignItems:"center",
      justifyContent:"space-between",
      paddingHorizontal: 12,
      borderBottomColor: "black",
      borderBottomWidth: 1,
      paddingBottom: 12,
    },
    boxVerseModal: {
        //flex: 1,
        marginBottom: 3,
        //backgroundColor: "white",
        borderRadius: 20,
        padding: 6,  
      },
    modalTitle: {
        fontSize: 18,
        color: "black",
    },
    modalButton: {
        fontSize: 14,
        color: "black",
        fontWeight: 600,
    },
  });

  export default styles;